name: Clean Repo and Init Submodules

on:
  workflow_dispatch:

jobs:
  clean-and-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo ohne Submodule
        uses: actions/checkout@v4
        with:
          ref: alpha
          fetch-depth: 0
          submodules: false

      - name: Update submodule URLs with token (automatisch aus .gitmodules)
        run: |
          # Token in URLs einfügen und gitmodules updaten
          token="${{ secrets.PAT_TOKEN }}"
          git config -f .gitmodules --get-regexp 'submodule\..*\.url' | while read key url; do
            url_with_token="${url/https:\/\/github.com/https://${token}@github.com/}"
            git config -f .gitmodules "$key" "$url_with_token"
            echo "Updated $key"
          done
          git submodule sync

      - name: Deinit alle Submodule
        run: git submodule deinit -f --all || echo "Keine Submodule zum deinit"

      - name: Submodule Cache löschen
        run: rm -rf .git/modules

      - name: Untracked Dateien und Ordner löschen
        run: git clean -fdx

      - name: Submodule neu initialisieren und updaten
        run: git submodule update --init --recursive

      - name: Submodule auf dev-Branch setzen und pullen
        run: |
          git submodule foreach --recursive '
            if git show-ref --verify --quiet refs/heads/dev; then
              git checkout dev
              git pull origin dev
            else
              echo "Kein dev-Branch in $name"
            fi
          '
