name: Manual Clean and Checkout Submodules

on:
  workflow_dispatch:  # nur manuell startbar

jobs:
  clean-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ohne Submodule
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Deinit alle Submodule
        run: |
          git submodule deinit -f --all || echo "Keine Submodule zum deinit"

      - name: Submodule-Cache löschen
        run: rm -rf .git/modules

      - name: Untracked Dateien und Ordner löschen
        run: git clean -fdx

      - name: Vollständig neu mit Submodulen auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Auf dev-Branch wechseln (Hauptrepo)
        run: git checkout dev

      - name: Submodule auf dev-Branch setzen und pullen
        run: |
          git submodule foreach --recursive '
            if git show-ref --verify --quiet refs/heads/dev; then
              git checkout dev;
              git pull origin dev;
            else
              echo "Kein dev-Branch in $name";
            fi
          '
