name: Create release on subrepo update

on:
  repository_dispatch:
    types: [subrepo-updated]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ github.event.client_payload.version }}"
          name: "Release ${{ github.event.client_payload.version }}"
          body: "Release triggered by push to ${{ github.event.client_payload.source }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
